KoNLPy 설치 (https://ingu627.github.io/tips/install_konlpy/)
1. java 설치
- https://java.com/ko/download/manual.jsp
- Python이 64비트면 Java도 64비트여야 한다. 32비트인 경우도 같다

2. 환경변수 설정
- java 설치 후 환경 변수 설정 필요
  - C:\Program Files\Java\jre1.8.0_241 설치 경로 확인 
- 제어판/시스템 및 보안/고급 시스템 설정/고급/환경 변수
- 새로만들기(N) 클릭
- 변수명:JAVA_HOME, 값: C:\Program Files\Java\jre1.8.0_241 입력

3. Jpype 설치
  - 이제 JAVA와 Python을 연결해주는 역할을 하는 JPype를 설치해야 합니다.
- 설치 주소 : https://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype
- JPype1‑1.3.0‑cp38‑cp38‑win_amd64.whl   (Python3.8/window64 bit)
- pip install JPype1‑1.3.0‑cp38‑cp38‑win_amd64.whl

4. KoNLPy 설치
 - pip install konlpy


In [6]:
!pip install konlpy

In [ ]:
!pip install --upgrade --force-reinstall JPype1

In [ ]:
!pip install blosc2 cython

In [4]:
!pip install --upgrade tables


In [1]:
# 형태소 분석 
# pos는 part of speech의 약자로 한국어로는 품사를 의미한다.

from konlpy.tag import Komoran
tagger = Komoran()  # 형태소 분석기
tagger.pos('한국어로 텍스트를 분석해 봅시다.')  # 형태소 분석
[('한국어', 'NNP'),
 ('로', 'JKB'),
 ('텍스트', 'NNG'),
 ('를', 'JKO'),
 ('분석', 'NNG'),
 ('하', 'XSV'),
 ('아', 'EC'),
 ('보', 'VX'),
 ('ㅂ시다', 'EF'),
 ('.', 'SF')]


[('한국어', 'NNP'),
 ('로', 'JKB'),
 ('텍스트', 'NNG'),
 ('를', 'JKO'),
 ('분석', 'NNG'),
 ('하', 'XSV'),
 ('아', 'EC'),
 ('보', 'VX'),
 ('ㅂ시다', 'EF'),
 ('.', 'SF')]

In [97]:
tagger.pos('한국어로 텍스트를 분석해 봅시다.')

[('한국어', 'NNP'),
 ('로', 'JKB'),
 ('텍스트', 'NNP'),
 ('를', 'JKO'),
 ('분석', 'NNG'),
 ('하', 'XSV'),
 ('아', 'EC'),
 ('보', 'VX'),
 ('ㅂ시다', 'EF'),
 ('.', 'SF')]

In [6]:
from konlpy.tag import Twitter
tagger = Twitter()  # 형태소 분석기
tagger.pos('한국어로 텍스트를 분석해 봅시다.')  # 형태소 분석

C:\Users\jaeyeon\anaconda3\Lib\site-packages\konlpy\tag\_okt.py:17: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


[('한국어', 'Noun'),
 ('로', 'Josa'),
 ('텍스트', 'Noun'),
 ('를', 'Josa'),
 ('분석', 'Noun'),
 ('해', 'Verb'),
 ('봅시다', 'Verb'),
 ('.', 'Punctuation')]

In [99]:
tagger.morphs('당신은 누구의 자랑인가?')

['당신', '은', '누구', '의', '자랑', '인가', '?']

많은 경우 명사만을 뽑아 텍스트 분석을 실시한다.
코모란의 경우 .nouns 메소드로 명사만을 추출할 수 있다.

tagger.nouns('한국어로 텍스트를 분석해 봅시다.')  # 명사 추출
['한국어', '텍스트', '분석']
만약 형태소 단위로 문자열을 끊고 싶다면, .morphs()를 사용하면 된다.

tagger.morphs()에 이전에 사용했던 문장을 넘겨주자.


In [100]:
tagger.nouns('한국어로 텍스트를 분석해 봅시다.')  # 명사 추출

['한국어', '텍스트', '분석']

In [101]:
tagger.morphs(' 한국어로 텍스트를 분석해 봅시다.')

['한국어', '로', '텍스트', '를', '분석', '해', '봅시다', '.']

아마존 제품 리뷰 TDM
1. 데이터 다운로드
- Amazon 사용자들이 올린 제품 리뷰를 TDM으로 만들어보자. UCI 머신러닝 리포지토리에서에서 Sentiment Labelled Sentences 데이터를 다운받아 'amazon_cells_labelled.txt'를 사용한다.
- https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences

2. 데이터 불러 오기
 - 아마존 제품 리뷰 자료는 한줄 댓글과 함께 해당 제품에 대한 긍/부정 점수가 1과 0으로 기록되어 있다. 따라서 긍/부정 감정사전을 만드는데 용이하다.
- 자료는 탭으로 구분이 이뤄져있으며, 열마다 제목이 없기 때문에 파일을 읽을 때 sep="\t" 옵션과 header=None 옵션을 넘겨줘야 한다


In [102]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Desktop\sentiment labelled sentences\amazon_cells_labelled.txt', sep="\t", header=None)

In [103]:
df.head(5)

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [104]:
content = df[0]
sentiment = df[1]
content,sentiment

(0      So there is no way for me to plug it in here i...
 1                            Good case, Excellent value.
 2                                 Great for the jawbone.
 3      Tied to charger for conversations lasting more...
 4                                      The mic is great.
                              ...                        
 995    The screen does get smudged easily because it ...
 996    What a piece of junk.. I lose more calls on th...
 997                         Item Does Not Match Picture.
 998    The only thing that disappoint me is the infra...
 999    You can not answer calls with the unit, never ...
 Name: 0, Length: 1000, dtype: object,
 0      0
 1      1
 2      1
 3      0
 4      1
       ..
 995    0
 996    0
 997    0
 998    0
 999    0
 Name: 1, Length: 1000, dtype: int64)

In [105]:
#3. TDM 만들기

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english',
                        lowercase=True,
                        max_features=1000)
tdm = tfidf.fit_transform(content)
tdm.shape

(1000, 1000)

In [106]:
print(tdm)

  (0, 884)	0.6336922128405843
  (0, 485)	0.5269561029030132
  (0, 942)	0.5663492253004965
  (1, 912)	0.6392095406476104
  (1, 255)	0.47823718132718357
  (1, 146)	0.4710276120116065
  (1, 306)	0.3752776975307017
  (2, 355)	0.8909828883166824
  (2, 310)	0.4540368847647319
  (3, 518)	0.3180236844892277
  (3, 407)	0.3548643091675774
  (3, 20)	0.4294194741822417
  (3, 368)	0.40528919670525015
  (3, 185)	0.3881684923718809
  (3, 155)	0.2986569556075369
  (3, 818)	0.4294194741822417
  (4, 405)	0.8844341363224174
  (4, 310)	0.4666650388743726
  (5, 922)	0.4177530356423377
  (5, 205)	0.492450330030864
  (5, 631)	0.4177530356423377
  (5, 379)	0.478197306613838
  (5, 485)	0.4240103899941458
  (6, 681)	0.6946954649786787
  (6, 183)	0.719303976728933
  :	:
  (993, 220)	1.0
  (994, 363)	1.0
  (995, 842)	0.4536703935039088
  (995, 747)	0.4536703935039088
  (995, 245)	0.3845968106507796
  (995, 266)	0.3960600022507811
  (995, 667)	0.34648694051732204
  (995, 225)	0.29240308948395255
  (995, 237)	0.279

In [107]:
tfidf.get_feature_names_out()

array(['10', '100', '11', '12', '13', '15', '15g', '18', '20', '2000',
       '2005', '2160', '24', '2mp', '325', '350', '375', '3o', '42', '44',
       '45', '4s', '50', '5020', '510', '5320', '680', '700w', '8125',
       '8525', '8530', 'abhor', 'ability', 'able', 'abound', 'absolutel',
       'absolutely', 'ac', 'accept', 'acceptable', 'access', 'accessory',
       'accessoryone', 'accidentally', 'accompanied', 'actually', 'ad',
       'adapter', 'adapters', 'add', 'addition', 'additional', 'address',
       'adhesive', 'adorable', 'advertised', 'advise', 'aggravating',
       'ago', 'alarm', 'allot', 'allow', 'allowing', 'allows', 'alot',
       'aluminum', 'amazed', 'amazing', 'amazon', 'amp', 'ample',
       'angeles', 'angle', 'answer', 'ant', 'antena', 'anti', 'apart',
       'apartment', 'apparently', 'appealing', 'appearance', 'appears',
       'applifies', 'appointments', 'area', 'arguing', 'armband',
       'arrival', 'arrived', 'asia', 'ask', 'aspect', 'assumed',
       '

In [108]:
# tdm의 정보 확인 가능
#  - tfidf 뒤에 .get_feature_names_out() 메써드를 부르면 TDM에 사용된 feature 단어 목록을 볼 수 있다. 
#  - 마지막 10개의 단어만 살펴보자

tfidf.get_feature_names_out()[-10:]

array(['worthless', 'worthwhile', 'wouldn', 'wow', 'wrong', 'wrongly',
       'year', 'years', 'yell', 'yes'], dtype=object)

In [109]:
# from sklearn.externals import joblib

with open('amazon.pkl', 'rb') as f:
    data = joblib.load(f)
    locals().update(data)
Count = tdm.sum(axis=0)
Count

matrix([[ 1.76034794,  0.46521938,  0.51050599,  0.47327189,  0.81124278,
          0.48895273,  0.51932284,  0.37958827,  0.70603291,  0.52515773,
          0.46389436,  0.3966342 ,  0.33259944,  0.40192999,  0.40273484,
          0.40513104,  0.40373467,  0.40097101,  0.49321969,  0.4257456 ,
          0.42941947,  0.37253524,  1.17998944,  0.33259944,  1.25277118,
          0.64296325,  0.63859278,  0.35543352,  0.48095155,  0.51694636,
          0.5343188 ,  0.6246444 ,  0.81343481,  1.85628524,  0.72724445,
          0.78408949,  2.47784589,  0.36594895,  1.08441939,  0.72724445,
          0.98078323,  0.7131251 ,  0.79472748,  0.58547689,  0.77085026,
          1.38812138,  0.45418589,  0.49845349,  0.48900131,  0.45432884,
          0.42395857,  0.89124114,  0.30779093,  0.66002397,  1.23836425,
          0.89717198,  1.61853182,  1.        ,  1.75957145,  0.42216143,
          0.48274968,  0.461336  ,  0.48928136,  0.99275685,  0.51843768,
          0.37052941,  0.89613276,  0.

In [110]:
#4. 저장
# 향후에 감정분석에서 사용하기 위해 tfidf, tdm, 그리고 df 의 'sentiment' 열을 피클로 저장해두자. 
# joblib은 pickle과 비슷하게 파이썬의 값들을 저장해주는 라이브러리다. pickle에 비해서 수치 데이터를 더 효율적으로 저장한다.


import joblib
with open('amazon.pkl', 'wb') as f:
    joblib.dump(
        {'vectorizer': tfidf, 'tdm': tdm, 'sentiment': sentiment},
        f
    )

뉴스 TDM 생성
1. 데이터 다운로드
- 개방 공공 데이터 활용(전파누리 최신 뉴스)
- https://www.data.go.kr/data/15076857/fileData.do

2. 데이터 불러오기


In [2]:
import pandas as pd

df2 = pd.read_csv(r"C:\Users\jaeyeon\Desktop\한국방송통신전파진흥원_전파누리_최신뉴스_20230725.csv",
                 encoding='cp949',
                 engine='python' )

df2.shape
df2.head()
df2['내용']


0       <p><span>한국나노기술원(원장 서광석)은 국방&middot;의료&middot;...
1       <p><span>광주정보문화산업진흥원 컨소시엄은 의료&middot;헬스케어 AI융합...
2       <p><span>유영상 SK텔레콤 대표&middot;구현모 KT 대표&middot;...
3       <p><span>과학기술정보통신부와 정보통신산업진흥원(NIPA)이 주관하는 '인공지...
4       <p><span>과학기술정보통신부와 정보통신산업진흥원(NIPA)이 주관하는 'AI융...
                              ...                        
1394    <p><span>웹&nbsp;</span><span><a>크롤링</a></span>...
1395    <p><span><a>캄테크</a></span><span>는 조용함을 뜻하는 캄(c...
1396    <p><span>1967년 1월 16일. 정부는 한국 최초의 과학기술진흥법을 이날 ...
1397    <p><span>통합 발주된 공공정보화 사업에서 상용 소프트웨어(SW) 개발사가 받...
1398    <p><span>북유럽 화가 가운데 기억나는 사람이 있을까. 대부분 노르웨이 화가 ...
Name: 내용, Length: 1399, dtype: object

In [3]:
df2

제목  \
0     나노기술원, 중적외선 양자폭포레이저 에피웨이퍼 소재 국산화 플랫폼 구축     작은...   
1     [AI 융합, 지역특화산업 디지털대전환 엔진]〈6〉 광주 의료·헬스케어 산업, AI...   
2     이통 3사 CEO 무선국·탄소배출 등 규제 개선 건의...주파수 할당은 인식차   ...   
3     [AI 융합, 지역특화산업 디지털대전환 엔진]〈3〉 유디엠텍·인터엑스·제이에스시스템...   
4     [AI 융합, 지역특화산업의 디지털대전환 엔진]〈1〉동서정보기술·에스피파트너스, 차...   
...                                                 ...   
1394                                      [ICT 시사용어]크롤링   
1395                                       [ICT시사용어]캄테크   
1396                                       과학기술진흥법 첫 제정   
1397                                        [관망경]유지관리요율   
1398                                          AI와 문화국가론   

                                                     내용  조회수    출저  
0     <p><span>한국나노기술원(원장 서광석)은 국방&middot;의료&middot;...    0  전자신문  
1     <p><span>광주정보문화산업진흥원 컨소시엄은 의료&middot;헬스케어 AI융합...    1  전자신문  
2     <p><span>유영상 SK텔레콤 대표&middot;구현모 KT 대표&middot;...    0  전자신문  
3     <p><span>과학기술정보통신부와 정보통신산업진흥원(NIPA)이 주관하는 '인공지...    0  전자신문  
4     <p><span>과학기술정보통신부와 정보통신산업진흥원(NIPA)이 주관하는 'AI융...    0  전자신문  
...                                                 ...  ...   ...  
1394  <p><span>웹&nbsp;</span><span><a>크롤링</a></span>...    1  전자신문  
1395  <p><span><a>캄테크</a></span><span>는 조용함을 뜻하는 캄(c...    1  전자신문  
1396  <p><span>1967년 1월 16일. 정부는 한국 최초의 과학기술진흥법을 이날 ...    7  전자신문  
1397  <p><span>통합 발주된 공공정보화 사업에서 상용 소프트웨어(SW) 개발사가 받...    0  전자신문  
1398  <p><span>북유럽 화가 가운데 기억나는 사람이 있을까. 대부분 노르웨이 화가 ...    0  전자신문  

[1399 rows x 4 columns]

In [ ]:
#last_row = df2.tail(1)
last_row = df2.tail(1).iloc[0]
taggers=[]
for i in range(last_row):
   taggers=taggers.append(tagger.nouns(str(df2['내용'].iloc[i])))

In [8]:
# 기존 코드에서 taggers 리스트를 초기화해야 함
taggers = []

last_row_length = len(df2.tail(1).iloc[0])
for i in range(last_row_length):
    taggers.append(tagger.nouns(str(df2['내용'].iloc[i])))


In [9]:
last_row = df2.tail(1)  # 마지막 행을 선택하여 데이터프레임으로 저장

taggers = []  # 결과를 저장할 리스트 초기화

# 데이터프레임의 마지막 행을 반복하여 처리
for i, row in last_row.iterrows():
    taggers.append(tagger.nouns(str(row['내용'])))

# taggers 리스트에는 마지막 행에 대한 형태소 분석 결과가 저장됩니다.


In [10]:
taggers

[['북유럽',
  '화가',
  '가운데',
  '사람',
  '대부분',
  '노르웨이',
  '화가',
  '에드',
  '뭉크',
  '핏빛',
  '하늘',
  '밑',
  '다리',
  '난관',
  '서서',
  '공포',
  '얼굴',
  '작품',
  '절규',
  '로',
  '부모',
  '형제',
  '죽음',
  '정신병',
  '고통',
  '고독',
  '질투',
  '불안',
  '공포',
  '그림',
  '세',
  '작품',
  '성은',
  '기본',
  '말',
  '것',
  '사무실',
  '거실',
  '그림',
  '세계',
  '명성',
  '이유',
  '뭘',
  '직전',
  '모든',
  '작품',
  '수도',
  '오슬로',
  '시',
  '기증',
  '노르웨이',
  '미술관',
  '건립',
  '개인',
  '정리',
  '마케팅',
  '적극',
  '결과',
  '대성공',
  '뭉크',
  '창작',
  '북유럽',
  '문화',
  '승화',
  '순간']]

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [12]:
# 혹은 직접 만든 함수를 사용할수도 있다. 
# 예시로 단어의 길이가 2 이상인 단어만 추출하는 함수를 만들어보자.

def get_nouns(text):
    nouns = tagger.nouns(text)
    nouns = [word for word in nouns if len(word) > 1]
    return nouns

get_nouns('아침에 해를 보며 버스를 탔다')
#

['아침', '버스']

CountVectorizer 안에 많은 옵션을 지정해 설정할 수 있다.

•	max_features=: TDM에 사용할 최대(max) 단어(feature) 수를 지정할 수 있다.
•	stop_words=: 영어의 경우 'a', 'the' 와 같은 불필요한 단어를 제거할 수 있다.
•	tokenizer=: token(feature)를 만들 때 적용하고 싶은 함수를 지정할 수 있다. 

한국어의 경우 형태소 분석 함수를 지정한다.


In [13]:
# 4. countvectorizer
# Scikit-learn에서 제공하는 TDM 만드는 모듈인 CountVectorizer를 불러온다. 
# CountVectorizer는 토큰이 문서별로 몇 번 등장했는지 행렬로 정리해주는 모듈이다.

cv = CountVectorizer(max_features=1000, tokenizer=get_nouns)

5. TDM생성
TDM은 cv 뒤에 .fit_transform() 메써드로 만들 수 있다. 형태소 분석을 같이 하기 때문에 시간이 오래 걸릴 수 있다.
•	.fit(): 단어 문서 행렬의 형태를 정하는 메소드로, 각 열에 들어갈 단어를 결정한다. 이 정보는 cv의 내부에 저장된다.
•	.transform(): .fit()으로 정한 단어에 데이터를 끼워 맞춘다.
•	fit_transform은 fit과 transform 두 개의 메소드를 합친 것이다.


In [14]:
cv

CountVectorizer(max_features=1000,
                tokenizer=<function get_nouns at 0x00000153C9ABE7A0>)

In [15]:
tdm = cv.fit_transform(df2['내용'])
cv.get_feature_names_out()[:10]  # 첫 10 단어


C:\Users\jaeyeon\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array(['가격', '가구', '가능성', '가동', '가망', '가상', '가상현실', '가상화', '가속', '가운데'],
      dtype=object)

In [16]:
print(tdm[0:5])

  (0, 932)	1
  (0, 581)	1
  (0, 131)	1
  (0, 609)	1
  (0, 881)	1
  (0, 987)	1
  (0, 506)	1
  (0, 294)	1
  (0, 429)	1
  (0, 132)	1
  (0, 921)	1
  (0, 124)	1
  (1, 609)	2
  (1, 108)	1
  (1, 714)	1
  (1, 281)	1
  (1, 385)	2
  (1, 801)	1
  (1, 857)	1
  (1, 605)	1
  (1, 376)	1
  (1, 888)	1
  (1, 218)	1
  (1, 212)	1
  (1, 159)	1
  :	:
  (3, 157)	1
  (3, 153)	1
  (3, 351)	1
  (3, 397)	1
  (4, 385)	3
  (4, 801)	1
  (4, 605)	1
  (4, 376)	1
  (4, 159)	1
  (4, 60)	1
  (4, 97)	1
  (4, 719)	1
  (4, 788)	1
  (4, 718)	1
  (4, 751)	1
  (4, 786)	1
  (4, 82)	1
  (4, 160)	1
  (4, 815)	1
  (4, 157)	1
  (4, 351)	1
  (4, 715)	1
  (4, 901)	1
  (4, 659)	1
  (4, 956)	1


In [17]:
cv.get_feature_names_out()

array(['가격', '가구', '가능성', '가동', '가망', '가상', '가상현실', '가상화', '가속', '가운데',
       '가이드라인', '가입', '가입자', '가장', '가지', '가치', '가칭', '각각', '각국', '간담',
       '간섭', '갈등', '감소', '감시', '감안', '강화', '개국', '개념', '개막', '개발', '개방',
       '개선', '개시', '개월', '개인', '개인정보', '개정', '개정안', '개최', '개통', '개편',
       '갤럭시', '거나', '거래', '거리', '건물', '건의', '검사', '검증', '검토', '게임', '격차',
       '결과', '결정', '결합', '경기도', '경매', '경영', '경우', '경쟁', '경쟁력', '경제', '경찰',
       '경험', '계기', '계약', '계획', '고객', '고도', '고도화', '고려', '고속', '고속도로',
       '고시', '고정', '골자', '공간', '공개', '공고', '공공', '공공기관', '공공안전', '공급',
       '공동', '공사', '공식', '공용', '공유', '공인', '공장', '공정', '공통', '과거', '과도',
       '과정', '과제', '과학', '과학기술', '관계', '관계자', '관련', '관로', '관리', '관심',
       '관제', '관측', '광대역', '광역시', '광주', '광케이블', '교류', '교수', '교육', '교체',
       '교통', '교환', '구간', '구글', '구매', '구분', '구상', '구성', '구조', '구체', '구축',
       '구현', '국가', '국내', '국내외', '국립', '국민', '국방', '국산', '국정', '국제',
       '국토교통부', '국회', '규격', '규모', '규정', '규제', '그룹', '그린', '극복', '근거',

In [18]:
# 6. TF-IDF 변환
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
tdm2 = tfidf.fit_transform(tdm)


In [19]:
tdm2.shape, tdm[0:5].data

((1399, 1000),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=int64))

In [20]:
tdm[0],tdm[0].indices,tdm[0].data

(<1x1000 sparse matrix of type '<class 'numpy.int64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 array([124, 131, 132, 294, 429, 506, 581, 609, 881, 921, 932, 987]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [21]:
print(tdm[0])
print(tdm2[0])

  (0, 124)	1
  (0, 131)	1
  (0, 132)	1
  (0, 294)	1
  (0, 429)	1
  (0, 506)	1
  (0, 581)	1
  (0, 609)	1
  (0, 881)	1
  (0, 921)	1
  (0, 932)	1
  (0, 987)	1
  (0, 987)	0.17558919089080982
  (0, 932)	0.18345147040821388
  (0, 921)	0.2714983052651931
  (0, 881)	0.15784943617220268
  (0, 609)	0.33396754766185366
  (0, 581)	0.3453405629173944
  (0, 506)	0.3064065136271022
  (0, 429)	0.3646876812352085
  (0, 294)	0.3542670338538256
  (0, 132)	0.31867708226814645
  (0, 131)	0.34964426124984893
  (0, 124)	0.1729115745025113


In [22]:
# - CountVectroizer와 TF-IDF 단어 비교 비교

words = cv.get_feature_names_out()

# 0번째 인덱스 슬라이스(문자열 가져오기 위해), data는 벡터 값
for i, n in sorted(zip(tdm[0].indices, tdm[0].data)):
    print(words[i], n)
for i, n in sorted(zip(tdm2[0].indices, tdm2[0].data)):
    print(words[i], n)


구축 1
국방 1
국산 1
반도체 1
소재 1
양자 1
원장 1
의료 1
통신 1
플랫폼 1
한국 1
활용 1
구축 0.1729115745025113
국방 0.34964426124984893
국산 0.31867708226814645
반도체 0.3542670338538256
소재 0.3646876812352085
양자 0.3064065136271022
원장 0.3453405629173944
의료 0.33396754766185366
통신 0.15784943617220268
플랫폼 0.2714983052651931
한국 0.18345147040821388
활용 0.17558919089080982


In [23]:
#7. 저장

import joblib
with open('ai_news_count.pkl', 'wb') as f:
    joblib.dump({'vectorizer': cv, 'tdm': tdm}, f)

import joblib
with open('ai_news_tfidf.pkl', 'wb') as f:
    joblib.dump({'vectorizer': cv, 'tdm': tdm2}, f)

In [24]:
print(words[134])

국제
